<?xml version="1.0"?>
<package format="2">
  <name>amigo_bringup</name>
  <version>0.0.1</version>
  <description>
    Bringup package
  </description>

  <maintainer email="amc9897@rit.edu">Aaron Chan</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>picam_forwarder</build_depend>
  <build_depend>rosaria</build_depend>

  <build_export_depend>picam_forwarder</build_export_depend>
  <build_export_depend>rosaria</build_export_depend>

  <exec_depend>picam_forwarder</exec_depend>
  <exec_depend>rosaria</exec_depend>
   <exec_depend>semantic_nav</exec_depend>
</package>
