<?xml version="1.0"?>
<package format="2">
  <name>semantic_nav</name>
  <version>0.0.1</version>
  <description>Semantic navigation using VLM-based bearing and sonar</description>

  <maintainer email="amc9897@rit.edu">Aaron Chan</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>rospy</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>vlm_clip</exec_depend>
</package>
